name: Push

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.79]
        runner: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy
    - name: Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.rust }}-${{ matrix.runner }}
    - run: uname -a
    - run: cargo install --locked cargo-criterion
      if: matrix.rust == 'stable'
    - run: cargo fmt -- --check
      if: matrix.rust == 'stable'
    - run: cargo clippy -- --deny warnings
      if: matrix.rust == 'stable'
    - run: cargo test --release
    - run: cargo criterion
      if: matrix.rust == 'stable'

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: miri
    - name: Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: miri
    - run: cargo miri test
